name: CI-CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 🔥 Build WITHOUT cache (forces Angular rebuild)
      - name: Build Backend Image
        run: docker build --no-cache -t ${{ secrets.DOCKER_USERNAME }}/backend:v1.0 ./backend

      - name: Build Frontend Image
        run: docker build --no-cache -t ${{ secrets.DOCKER_USERNAME }}/frontend:v1.0 ./frontend

      - name: Push Backend Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/backend:v1.0

      - name: Push Frontend Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/frontend:v1.0
      # 🔥 Deploy to VM via SSH
      - name: Deploy to VM via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            PROJECT_DIR="/home/ubuntu/GitHub_action_assignment"
            REPO_URL="https://github.com/Yashwanthgowdam123/GitHub_action_assignment.git"

            # Clone repository only if it doesn't exist
            if [ ! -d "$PROJECT_DIR" ]; then
              echo "Project not found. Cloning repository..."
              git clone "$REPO_URL" "$PROJECT_DIR"
            else
              echo "Project already exists."
            fi

            cd "$PROJECT_DIR"

            # Install Docker only if it's not installed
            if ! command -v docker >/dev/null 2>&1; then
              echo "Docker not found. Installing..."
              chmod +x docker_installation.sh
              sudo ./docker_installation.sh
            else
              echo "Docker already installed."
            fi

            sudo docker compose down || true
            sudo docker compose pull
            sudo docker compose up -d --force-recreate
